
import LocalizedStrings from 'react-native-localization';
const StringsOfLanguages = new LocalizedStrings({
  en: {
    first: 'Sign Up',//
    second: 'Sign In ',
    third: 'Back',
    fourth: 'full name',
    fifth: 'ID number',
    sixth: 'email address',
    seventh: 'password',
    eighth: 'select nationality',
    ninth: 'NEXT',
    tenth: 'Address',
    eleven: 'Date Of Birth',
    twelve:{
      1:'city',
      2:'Amman',
      3:'Zarga',
      4:'Irbid',
      5:'Russeifa',
      6:'Al-Quwaysimah',
      7:'Tila al-Ali',
      8:'Wadi as-Ser',
      9:'al-Jubayhah',
      10:'Khuraybat as-Suq',
      11:'sahab',
      12:'Ar Ramtha',
      13:'Suwaylih',
      14:'Aqaba',
      15:'Zaatari refugee camp',
      16:'Mafraq',
      17:'Madaba'
    },
      thirteen:'Type Of Training',
      fourteen:'Automatic Car',
      fifteen:'Manual Car',
      sixteen:'Capture Your National identification Card',
      seventeen:'Press on the camera and capture the font side of your ID in the frame',
      eighteen: 'Press on the camera and capture the back side of your ID in the frame',
      ninteen: 'GET STARTED',
      twenty: 'Sign in with your ID number and your password',
      twenty1: 'Forget Password?',
      twenty2: "Don't have an account?",
      twenty3: 'enter your ID below',
      twenty4: 'Submit',
      twenty5:'Please check your email',
      twenty6: 'and enter the code below',
      twenty7:'code',
      twenty8:"Didn't recieve a code?",
      twenty9:'Re-send code',
      thirty:'Reset Password',
      thirty1:'Enter the New Password',
      thirty2:'new password',
      thirty3:'confirm password',
      thirty4:'Profile',
      thirty5:'update profile',
      thirty6:'Phone',
      thirty7:'Update',
      thirty8:'Start Training',
      thirty9:'Your training hours must be qual 60 hours',
      fourty: 'Home',
      fourty1:'Reserve Exam',
      fourty2:'My Training',
      fourty3:'Settings',
      fourty4:'Help',
      fourty5:'Logout',
      fourty6:'ID must be 10 numbers',
      fourty7:"Password didn't match",
      fourty8:'select nationality',
      payment:"payment",
      bell:"inbox",
      Editprofile:"Edit your profile"
      


  },



  ar: {
    first: 'الاشتراك',
    second: 'تسجيل الدخول',
    third: 'الرجوع',
    fourth: 'الاسم الكامل',
    fifth: 'الرقم الوطني',
    sixth: 'البريد الإلكتروني',
    seventh: 'كلمة المرور',
    eighth: 'إختر الجنسية',
    ninth: 'التالي',
    tenth: 'العنوان',
    eleven: 'تاريخ الميلاد',
    twelve:{
      1:'المدينة',
      2:'عمان',
      3:'الزرقاء',
      4:'إربد',
      5:'الرصيفة',
      6:'القويسمة',
      7:'تلاع العلي',
      8:'وادي السير',
      9:'الجبيهة',
      10:'خريبة السوق',
      11:'سحاب',
      12:'الرمثا',
      13:'صويلح',
      14:'العقبة',
      15:'سوري إبن بلد مش لاجئ ',
      16:'المفرق',
      17:'مادبا'
    },
      thirteen:'نوع التدريب',
      fourteen:'أوتوماتيك',
      fifteen:'عادي',
      sixteen:'إلتقط صورة لهويتك الشخصية ',
      seventeen:'إلتقط صورة للوجه الأمامي من هويتك الشخصية',
      eighteen: 'إلتقط صورة للوجه الخلفي من هويتك الشخصية',
      ninteen: 'إبدأ الآن',
      twenty: 'سجل الدخول باستخدام رقمك الوطني وكلمة المرور',
      twenty1: 'هل نسيت كلمة السر ؟',
      twenty2: "ليس لديك حساب ؟",
      twenty3: 'أدخل الرقم الوطني',
      twenty4: 'تأكيد',
      twenty5:'الرجاء التحقق من البريد الإلكتروني',
      twenty6: 'وإدخال الرمز ',
      twenty7:'الرمز',
      twenty8:"لم يصلك الرمز ؟",
      twenty9:'إعادة إرسال الرمز',
      thirty:'إعادة تعيين كلمة المرور',
      thirty1:'أدخل كلمة مرور جديدة',
      thirty2:'كلمة مرور جديدة',
      thirty3:'تأكيد كلمة المرور',
      thirty4:'الملف الشخصي',
      thirty5:'تحديث الملف الشخصي',
      thirty6:'رقم الهاتف',
      thirty7:'تحديث',
      thirty8:'إبدأ التدريب',
      thirty9:'عدد ساعات التدريب يجب أن تكون 60 ساعة',
      fourty: 'الصفحة الرئيسية',
      fourty1:'إحجز للإمتحان',
      fourty2:'تدريبك',
      fourty3:'الإعدادات',
      fourty4:'مساعدة',
      fourty5:'تسجيل الخروج',
      fourty6:'الرقم الوطني يجب أن يتكون من 10 خانات ',
      fourty7:'كلمة المرور غير مطابقة',
      fourty8:'إختر الجنسية',
      payment:"الدفع",
      bell:"الوارد",
      Editprofile:"تعديل الصفحة الشخصية"
    },

  
});

export default StringsOfLanguages;
